# from pydantic import Field
# from pydantic_settings import BaseSettings
from pathlib import Path

# Paths
PROJ_ROOT = Path(__file__).resolve().parents[8]

DATA_DIR = PROJ_ROOT / "data"
LOGS_DIR = PROJ_ROOT / "logs"
SRC_DIR = PROJ_ROOT / "src"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

"""
class AppConfig(BaseSettings):
    DATA_DIR: Path = PROJ_ROOT / "data"
    RAW_DATA_DIR: Path = DATA_DIR / "raw"
    PROCESSED_DATA_DIR: Path = DATA_DIR / "processed"
    PHISHIRIS_DL_DATASET_DIR: Path = RAW_DATA_DIR / "phishIRIS_DL_Dataset"
    SAME_TARGET: dict[(str, str)] = Field(
        default_factory=lambda: {
            "Absa Group": "absa",
            "Amazon.com Inc.": "amazon",
            "Americanas.com S,A Comercio Electrnico": "americanas",
            "Americanas.com S_A Comercio Electrnico": "americanas",
            "Aruba S.p.A.": "aruba",
            "Barclays Bank Plc": "barclays",
            "Canada Revenue Agency": "canada",
            "Capital One Financial Corporation": "capital_one",
            "Capitec Bank Limited": "capitec",
            "Chase Personal Banking": "chase",
            "Commonwealth Bank of Australia": "commonwealth_bank",
            "Cox Communications": "cox",
            "DHL Airways, Inc.": "dhl",
            "grupo_bancolombia": "bancolombia",
            "Bancolombia": "bancolombia",
            "HSBC Bank": "hsbc",
            "Itau Unibanco S.A": "itau",
            "La Banque postale": "la_banque_postale",
            "Lloyds TSB Group": "lloyds",
            "lloyds_bank": "lloyds",
            "Made-In-China": "made_in_china",
            "Microsoft OneDrive": "onedrive",
            "ms_onedrive": "onedrive",
            "ms_bing": "bing",
            "ms_office": "ms_office",
            "Office365": "ms_office",
            "National Australia Bank Limited": "nab",
            "NatWest Personal Banking": "natwest",
            "Navy Federal Credit Union": "navy_federal",
            "NedBank Limited": "nedbank",
            "OurTime Dating": "ourtime",
            "Outlook": "outlook",
            "ms_outlook": "outlook",
            "RBC Royal Bank": "rbc",
            "Sparkasse Bank": "sparkasse",
            "Standard Chartered Bank": "standard_bank",
            "Strato AG": "strato",
            "SunTrust Bank": "suntrust",
            "Swisscom IT Services AG": "swisscom",
            "Telecom Italia": "telecom",
            "Wells Fargo & Company": "wells_fargo",
            "Bank of America": "boa",
        }
    )
    TARGET_URL: dict[(str, str)] = Field(
        {
            "absa": "https://www.absa.co.za",
            "adidas": "https://www.adidas.com",
            "adobe": "https://www.adobe.com",
            "airbnb": "https://www.airbnb.com",
            "alibaba": "https://www.alibaba.com",
            "aliexpress": "https://www.aliexpress.com",
            "allegro": "https://www.allegro.pl",
            "amazon": "https://www.amazon.com",
            "ameli_fr": "https://www.ameli.fr",
            "american_express": "https://www.americanexpress.com",
            "anadolubank": "https://www.anadolubank.com.tr",
            "aol": "https://www.aol.com",
            "apple": "https://www.apple.com",
            "arnet_tech": "https://www.arnettech.com",
            "aruba": "https://www.aruba.it",
            "att": "https://www.att.com",
            "azul": "https://www.voeazul.com.br",
            "bahia": "https://www.bahia.com.br",
            "banco_de_occidente": "https://www.bancodeoccidente.com",
            "banco_inter": "https://www.bancointer.com.br",
            "bankia": "https://www.bankia.com",
            "barclaycard": "https://www.barclaycard.co.uk",
            "barclays": "https://www.barclays.co.uk",
            "bbt": "https://www.bbt.com",
            "bcp": "https://www.viabcp.com",
            "bestchange": "https://www.bestchange.com",
            "blizzard": "https://www.blizzard.com",
            "bmo": "https://www.bmo.com",
            "bnp_paribas": "https://www.bnpparibas.com",
            "bnz": "https://www.bnz.co.nz",
            "boa": "https://www.bankofamerica.com",
            "bradesco": "https://www.bradesco.com.br",
            "bt": "https://www.bt.com",
            "caixa_bank": "https://www.caixabank.com",
            "canada": "https://www.canada.ca",
            "capital_one": "https://www.capitalone.com",
            "capitec": "https://www.capitecbank.co.za",
            "cathay_bank": "https://www.cathaybank.com",
            "cetelem": "https://www.cetelem.fr",
            "chase": "https://www.chase.com",
            "cibc": "https://www.cibc.com",
            "cloudconvert": "https://www.cloudconvert.com",
            "cloudns": "https://www.cloudns.net",
            "cogeco": "https://www.cogeco.ca",
            "commonwealth_bank": "https://www.commbank.com.au",
            "cox": "https://www.cox.com",
            "crate_and_barrel": "https://www.crateandbarrel.com",
            "cryptobridge": "https://www.crypto-bridge.org",
            "daum": "https://www.daum.net",
            "db": "https://www.db.com",
            "dhl": "https://www.dhl.com",
            "dkb": "https://www.dkb.de",
            "docmagic": "https://www.docmagic.com",
            "dropbox": "https://www.dropbox.com",
            "ebay": "https://www.ebay.com",
            "eharmony": "https://www.eharmony.com",
            "erste": "https://www.erstebank.com",
            "etisalat": "https://www.etisalat.ae",
            "etrade": "https://www.etrade.com",
            "facebook": "https://www.facebook.com",
            "fibank": "https://www.fibank.bg",
            "file_transfer": "https://www.filetransfer.io",
            "fnac": "https://www.fnac.com",
            "fsnb": "https://www.fsnb.com",
            "godaddy": "https://www.godaddy.com",
            "google": "https://www.google.com",
            "gov_uk": "https://www.gov.uk",
            "grupo_bancolombia": "https://www.grupobancolombia.com",
            "hfe": "https://www.hfe.com",
            "hsbc": "https://www.hsbc.com",
            "htb": "https://www.htb.co.uk",
            "ics": "https://www.icscards.nl",
            "ieee": "https://www.ieee.org",
            "impots_gov": "https://www.impots.gouv.fr",
            "infinisource": "https://www.infinisource.com",
            "instagram": "https://www.instagram.com",
            "irs": "https://www.irs.gov",
            "itau": "https://www.itau.com.br",
            "knab": "https://www.knab.nl",
            "la_banque_postale": "https://www.labanquepostale.fr",
            "la_poste": "https://www.laposte.fr",
            "latam": "https://www.latam.com",
            "lbb": "https://www.lbb.de",
            "lcl": "https://www.lcl.fr",
            "linkedin": "https://www.linkedin.com",
            "lloyds_bank": "https://www.lloydsbank.com",
            "made_in_china": "https://www.made-in-china.com",
            "mbank": "https://www.mbank.pl",
            "mdpd": "https://www.miamidade.gov/police",
            "mew": "https://www.myetherwallet.com",
            "microsoft": "https://www.microsoft.com",
            "momentum_office_design": "https://www.momentumofficedesign.com",
            "mweb": "https://www.mweb.co.za",
            "my_cloud": "https://www.mycloud.com",
            "nab": "https://www.nab.com.au",
            "natwest": "https://www.natwest.com",
            "navy_federal": "https://www.navyfederal.org",
            "nedbank": "https://www.nedbank.co.za",
            "netflix": "https://www.netflix.com",
            "netsons": "https://www.netsons.com",
            "nordea": "https://www.nordea.com",
            "ocn": "https://www.ocn.ne.jp",
            "one_and_one": "https://www.ionos.com",
            "orange": "https://www.orange.com",
            "orange_rockland": "https://www.oru.com",
            "otrs": "https://www.otrs.com",
            "ourtime": "https://www.ourtime.com",
            "paschoalotto": "https://www.paschoalotto.com.br",
            "paypal": "https://www.paypal.com",
            "postbank": "https://www.postbank.de",
            "qnb": "https://www.qnb.com",
            "rbc": "https://www.rbc.com",
            "runescape": "https://www.runescape.com",
            "sharp": "https://www.sharp.com",
            "shoptet": "https://www.shoptet.com",
            "sicil_shop": "https://www.sicilshop.com",
            "smartsheet": "https://www.smartsheet.com",
            "smiles": "https://www.smiles.com.br",
            "snapchat": "https://www.snapchat.com",
            "sparkasse": "https://www.sparkasse.de",
            "standard_bank": "https://www.standardbank.com",
            "steam": "https://www.steampowered.com",
            "strato": "https://www.strato.com",
            "stripe": "https://www.stripe.com",
            "summit_bank": "https://www.summitbank.com",
            "sunrise": "https://www.sunrise.ch",
            "suntrust": "https://www.suntrust.com",
            "swisscom": "https://www.swisscom.ch",
            "taxact": "https://www.taxact.com",
            "tech_target": "https://www.techtarget.com",
            "telecom": "https://www.telecom.com",
            "test_rite": "https://www.testritegroup.com",
            "timeweb": "https://www.timeweb.com",
            "tradekey": "https://www.tradekey.com",
            "twins_bnk": "https://www.twinsbank.com",
            "twitter": "https://www.twitter.com",
            "typeform": "https://www.typeform.com",
            "usaa": "https://www.usaa.com",
            "walmart": "https://www.walmart.com",
            "wells_fargo": "https://www.wellsfargo.com",
            "whatsapp": "https://www.whatsapp.com",
            "wp60": "https://www.wp60.com",
            "xtrix_tv": "https://www.xtrixtv.com",
            "yahoo": "https://www.yahoo.com",
            "youtube": "https://www.youtube.com",
            "ziggo": "https://www.ziggo.nl",
            "google_drive": "https://www.google.com/drive",
            "ms_skype": "https://www.skype.com",
            "ms_onedrive": "https://www.onedrive.com",
            "ms_outlook": "https://www.outlook.com",
            "ms_bing": "https://www.bing.com",
            "ms_office": "https://www.office.com",
            "itunes": "https://www.apple.com/itunes",
            "icloud": "https://www.icloud.com",
            "zoominfo": "https://www.zoominfo.com",
        }
    )


config = AppConfig()
"""
